#This module contains the admin frame and its functionalities.
from PyQt5 import QtCore, QtGui, QtWidgets
from Database import *
class Ui_adminFrame(object):
    def setupUi(self, adminFrame):
        adminFrame.setObjectName("adminFrame")
        adminFrame.resize(700, 700)
        adminFrame.setMinimumSize(QtCore.QSize(700, 700))
        adminFrame.setMaximumSize(QtCore.QSize(16777215, 16722215))
        adminFrame.setFrameShape(QtWidgets.QFrame.Box)
        adminFrame.setLineWidth(1)
        self.verticalLayout = QtWidgets.QVBoxLayout(adminFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        #search area
        self.searchArea = QtWidgets.QFrame(adminFrame)
        self.searchArea.setMinimumSize(QtCore.QSize(0, 120))
        self.searchArea.setMaximumSize(QtCore.QSize(16777215, 200))
        self.searchArea.setStyleSheet("background:rgb(255, 255, 255)")
        self.searchArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchArea.setObjectName("searchArea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.searchArea)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #search section
        self.srchFrame = QtWidgets.QFrame(self.searchArea)
        self.srchFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.srchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srchFrame.setObjectName("srchFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.srchFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(self.srchFrame)
        self.frame_11.setMaximumSize(QtCore.QSize(720, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        #search symbol
        self.symbol = QtWidgets.QLabel(self.frame_11)
        self.symbol.setMaximumSize(QtCore.QSize(50, 50))
        self.symbol.setText("")
        self.symbol.setPixmap(QtGui.QPixmap("icons/2.png"))
        self.symbol.setScaledContents(True)
        self.symbol.setObjectName("symbol")
        self.horizontalLayout_8.addWidget(self.symbol, 0, QtCore.Qt.AlignVCenter)
        #user name label
        self.uid = QtWidgets.QLabel(self.frame_11)
        self.uid.setMinimumSize(QtCore.QSize(150, 50))
        self.uid.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uid.setFont(font)
        self.uid.setStyleSheet("border:none;")
        self.uid.setScaledContents(False)
        self.uid.setWordWrap(False)
        self.uid.setObjectName("uid")
        self.horizontalLayout_8.addWidget(self.uid, 0, QtCore.Qt.AlignVCenter)
        #user name input section
        self.unInp = QtWidgets.QTextEdit(self.frame_11)
        self.unInp.setMinimumSize(QtCore.QSize(100, 40))
        self.unInp.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unInp.setFont(font)
        self.unInp.setStyleSheet("border: 2px solid black;\n"
                                    "border-radius:15px;")
        self.unInp.setObjectName("unInp")
        self.horizontalLayout_8.addWidget(self.unInp, 0, QtCore.Qt.AlignVCenter)
        #search button
        self.srchBtn = QtWidgets.QPushButton(self.frame_11)
        self.srchBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.srchBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.srchBtn.setToolTip("Search User")
        self.srchBtn.setAutoFillBackground(False)
        self.srchBtn.setStyleSheet("background:rgb(255,255,255)")
        self.srchBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/srch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.srchBtn.setIcon(icon)
        self.srchBtn.setIconSize(QtCore.QSize(40, 40))
        self.srchBtn.setFlat(True)
        self.srchBtn.setObjectName("srchBtn")
        self.srchBtn.clicked.connect(self.search)
        self.horizontalLayout_8.addWidget(self.srchBtn, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.verticalLayout_2.addWidget(self.srchFrame)
        #edit section
        self.editFrame = QtWidgets.QFrame(self.searchArea)
        self.editFrame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.editFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editFrame.setObjectName("editFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.editFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.editFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgb(170, 170, 255);\n"
                                    "border-top-right-radius:15px;\n"
                                    "border-top-left-radius:15px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        # load frame
        self.loadFrame = QtWidgets.QFrame(self.frame)
        self.loadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadFrame.setObjectName("loadFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.loadFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        #load label
        self.load = QtWidgets.QLabel(self.loadFrame)
        self.load.setMaximumSize(QtCore.QSize(75, 75))
        self.load.setObjectName("load")
        self.load.setScaledContents(True)
        self.movie=QtGui.QMovie("icons/load.gif")
        self.load.setMovie(self.movie)
        self.load.hide()
        self.horizontalLayout_9.addWidget(self.load)
        self.horizontalLayout_2.addWidget(self.loadFrame)
        self.horizontalLayout.addWidget(self.frame)
        #button section
        self.btnFrame = QtWidgets.QFrame(self.editFrame)
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.btnFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #save button
        self.saveBtn = QtWidgets.QPushButton(self.btnFrame)
        self.saveBtn.setEnabled(True)
        self.saveBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setToolTip("Save current Record")
        self.saveBtn.clicked.connect(self.save)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon1)
        self.saveBtn.setIconSize(QtCore.QSize(40, 40))
        self.saveBtn.setFlat(True)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_3.addWidget(self.saveBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        #edit button
        self.editBtn = QtWidgets.QPushButton(self.btnFrame)
        self.editBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.editBtn.setFont(font)
        self.editBtn.setToolTip("Edit current Record")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editBtn.setIcon(icon2)
        self.editBtn.setIconSize(QtCore.QSize(50, 50))
        self.editBtn.setFlat(True)
        self.editBtn.setObjectName("editBtn")
        self.editBtn.clicked.connect(self.edit)
        self.horizontalLayout_3.addWidget(self.editBtn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        #add button
        self.addBtn = QtWidgets.QPushButton(self.btnFrame)
        self.addBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setToolTip("Add new Record")
        self.addBtn.clicked.connect(self.add)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon3)
        self.addBtn.setIconSize(QtCore.QSize(40, 40))
        self.addBtn.setFlat(True)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout_3.addWidget(self.addBtn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        #delete button
        self.deleteBtn = QtWidgets.QPushButton(self.btnFrame)
        self.deleteBtn.setToolTip("Delete current Record")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBtn.setIcon(icon4)
        self.deleteBtn.setIconSize(QtCore.QSize(40, 40))
        self.deleteBtn.setFlat(True)
        self.deleteBtn.setObjectName("deleteBtn")
        self.deleteBtn.clicked.connect(self.delete)
        self.horizontalLayout_3.addWidget(self.deleteBtn)
        self.horizontalLayout.addWidget(self.btnFrame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.editFrame)
        self.verticalLayout.addWidget(self.searchArea)
        #detail section
        self.detailArea = QtWidgets.QFrame(adminFrame)
        self.detailArea.setMinimumSize(QtCore.QSize(0, 600))
        self.detailArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.detailArea.setStyleSheet("background:#ffffff")
        self.detailArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.detailArea.setObjectName("detailArea")
        self.gridLayout = QtWidgets.QGridLayout(self.detailArea)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.admin = QtWidgets.QFrame(self.detailArea)
        self.admin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin.setObjectName("admin")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.admin)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.adminTxt = QtWidgets.QFrame(self.admin)
        self.adminTxt.setMaximumSize(QtCore.QSize(500, 50))
        self.adminTxt.setStyleSheet("background:rgb(170, 170, 255);\n"
                                        "border-radius:15px;")
        self.adminTxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.adminTxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.adminTxt.setObjectName("adminTxt")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.adminTxt)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.logo_4 = QtWidgets.QLabel(self.adminTxt)
        self.logo_4.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_4.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_4.setText("")
        self.logo_4.setPixmap(QtGui.QPixmap("icons/5.png"))
        self.logo_4.setScaledContents(True)
        self.logo_4.setObjectName("logo_4")
        self.horizontalLayout_7.addWidget(self.logo_4)
        self.txt_4 = QtWidgets.QLabel(self.adminTxt)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_4.setFont(font)
        self.txt_4.setObjectName("txt_4")
        self.horizontalLayout_7.addWidget(self.txt_4)
        self.verticalLayout_7.addWidget(self.adminTxt)
        #admin detail section
        self.adminFrame_2 = QtWidgets.QFrame(self.admin)
        self.adminFrame_2.setStyleSheet("")
        self.adminFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.adminFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.adminFrame_2.setObjectName("adminFrame_2")
        self.formLayout = QtWidgets.QFormLayout(self.adminFrame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.adminFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        #user name i/o
        self.un = QtWidgets.QLineEdit(self.adminFrame_2)
        self.un.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.un.setFont(font)
        self.un.setStyleSheet("")
        self.un.setAlignment(QtCore.Qt.AlignCenter)
        self.un.setReadOnly(True)
        self.un.setObjectName("un")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.un)
        self.label_7 = QtWidgets.QLabel(self.adminFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        #password i/o
        self.pswd = QtWidgets.QLineEdit(self.adminFrame_2)
        self.pswd.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.pswd.setFont(font)
        self.pswd.setAlignment(QtCore.Qt.AlignCenter)
        self.pswd.setReadOnly(True)
        self.pswd.setObjectName("pswd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pswd)
        self.label_5 = QtWidgets.QLabel(self.adminFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        #name i/o
        self.name = QtWidgets.QLineEdit(self.adminFrame_2)
        self.name.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_9 = QtWidgets.QLabel(self.adminFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        #contact i/o
        self.mob = QtWidgets.QLineEdit(self.adminFrame_2)
        self.mob.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.mob.setFont(font)
        self.mob.setAlignment(QtCore.Qt.AlignCenter)
        self.mob.setReadOnly(True)
        self.mob.setObjectName("mob")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mob)
        self.verticalLayout_7.addWidget(self.adminFrame_2)
        self.gridLayout.addWidget(self.admin, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.detailArea)

        self.inps=[self.un,self.pswd,self.name,self.mob]
        self.retranslateUi(adminFrame)
        QtCore.QMetaObject.connectSlotsByName(adminFrame)
    def retranslateUi(self, adminFrame):
        _translate = QtCore.QCoreApplication.translate
        adminFrame.setWindowTitle(_translate("adminFrame", "adminFrame"))
        self.uid.setText(_translate("adminFrame", "User Name : "))
        self.unInp.setPlaceholderText(_translate("adminFrame", "Enter username/userId"))
        self.label.setText(_translate("adminFrame", "Basic Details"))
        self.txt_4.setText(_translate("adminFrame", "Admin / User Details"))
        self.label_8.setText(_translate("adminFrame", "Username"))
        self.un.setPlaceholderText(_translate("adminFrame", "N/A"))
        self.label_7.setText(_translate("adminFrame", "Password"))
        self.pswd.setPlaceholderText(_translate("adminFrame", "N/A"))
        self.label_5.setText(_translate("adminFrame", "Name"))
        self.name.setPlaceholderText(_translate("adminFrame", "N/A"))
        self.label_9.setText(_translate("adminFrame", "Contact"))
        self.mob.setPlaceholderText(_translate("adminFrame", "N/A"))
    def lineReadOnly(self,state):
        for lineEdit in self.inps:lineEdit.setReadOnly(state)
    def recOpen(self):
        flag=False
        for l in self.inps:
            if not l.text()=='':
                flag=True
                break
        return flag
    def recClose(self):
        for lineEdit in self.inps:lineEdit.clear()
        self.unInp.clear()
    def search(self):
        self.load.show()
        self.movie.start()
        self.lineReadOnly(True)
        srchUid=self.unInp.toPlainText()
        if not srchUid == '' and srchUid.isalnum():
            db=SMSDB()
            if db.check_exist(srchUid):
                rec=db.fetchAdmin(srchUid)
                for i in range(4):self.inps[i].setText(rec[i])
            else:show_msg('User not Found.')
            db.conn_close()
        else:show_msg('Enter valid input.')
        self.movie.stop()
        self.load.hide()
    def add(self):
        self.recClose()
        self.lineReadOnly(False)
        show_msg('Ready to add fields.')
    def save(self):
        if self.recOpen():
            if not self.un.isReadOnly():
                # fetching all data from form
                un = self.un.text()
                nm = self.name.text()
                pswd = self.pswd.text()
                no = self.mob.text()
                # applying validations
                for name in nm.split():
                    if not name.isalpha():
                        show_msg('Enter valid name.')
                        break
                if not un.isalnum():
                    show_msg('Enter valid user name.')
                elif not no.isdigit():
                    show_msg('Enter valid Mobile No.')
                elif len(no) != 10:
                    show_msg('Enter valid length Mobile No.')
                else:
                    db = SMSDB()  # connnecting DB
                    if db.insert_admin(un, pswd, nm, no):show_msg('Admin Registered.')
                    else:
                        if confirm_msg('User already exist.\nWant to Update Record'):
                            db.update_admin(un,pswd,nm,no)
                            show_msg('Record Updated.')
                    db.conn_close()  # disconnecting DB
                    self.recClose()
                    self.lineReadOnly(True)
            else:pass
        else:show_msg('No Record to Save.')
    def delete(self):
        if self.recOpen():
            if confirm_msg('Confirm to Delete'):
                db=SMSDB()
                db.delete_admin(self.un.text())
                show_msg('Record Deleted')
                db.conn_close()
                self.recClose()
                self.lineReadOnly(True)
        else:show_msg('No Record to Delete.')

    def edit(self):
        if self.recOpen():
            self.lineReadOnly(False)
            show_msg('Ready to edit fields.')
        else:show_msg('No Record to Edit.')

"""This is for trial run""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminFrame = QtWidgets.QFrame()
    ui = Ui_adminFrame()
    ui.setupUi(adminFrame)
    adminFrame.show()
    sys.exit(app.exec_())
"""