#This module contains the student frame and its functionalities.
from PyQt5 import QtCore, QtGui, QtWidgets
from Database import *
class Ui_studFrame(object):
    def setupUi(self, studFrame):
        studFrame.setObjectName("studFrame")
        studFrame.resize(700, 700)
        studFrame.setMinimumSize(QtCore.QSize(700, 700))
        studFrame.setMaximumSize(QtCore.QSize(16777215, 16722215))
        studFrame.setFrameShape(QtWidgets.QFrame.Box)
        studFrame.setLineWidth(1)

        self.verticalLayout = QtWidgets.QVBoxLayout(studFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        #head section
        self.searchArea = QtWidgets.QFrame(studFrame)
        self.searchArea.setMaximumSize(QtCore.QSize(16777215, 120))
        self.searchArea.setStyleSheet("background:rgb(255, 255, 255)")
        self.searchArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchArea.setObjectName("searchArea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.searchArea)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #search section
        self.srchFrame = QtWidgets.QFrame(self.searchArea)
        self.srchFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.srchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srchFrame.setObjectName("srchFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.srchFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(self.srchFrame)
        self.frame_11.setMaximumSize(QtCore.QSize(720, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        #registration no symbol
        self.symbol = QtWidgets.QLabel(self.frame_11)
        self.symbol.setMaximumSize(QtCore.QSize(50, 50))
        self.symbol.setText("")
        self.symbol.setPixmap(QtGui.QPixmap("icons/2.png"))
        self.symbol.setScaledContents(True)
        self.symbol.setObjectName("symbol")
        self.horizontalLayout_8.addWidget(self.symbol)
        #registration no label
        self.reg = QtWidgets.QLabel(self.frame_11)
        self.reg.setMinimumSize(QtCore.QSize(200, 50))
        self.reg.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reg.setFont(font)
        self.reg.setStyleSheet("border:none;")
        self.reg.setScaledContents(False)
        self.reg.setWordWrap(False)
        self.reg.setObjectName("reg")
        self.horizontalLayout_8.addWidget(self.reg)
        self.regNoInp = QtWidgets.QTextEdit(self.frame_11)
        self.regNoInp.setMinimumSize(QtCore.QSize(100, 40))
        self.regNoInp.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        #registration no input
        self.regNoInp.setFont(font)
        self.regNoInp.setStyleSheet("border: 2px solid black;\n"
                                        "border-radius:15px;")
        self.regNoInp.setObjectName("regNoInp")
        self.horizontalLayout_8.addWidget(self.regNoInp)
        #search button
        self.srchBtn = QtWidgets.QPushButton(self.frame_11)
        self.srchBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.srchBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.srchBtn.setAutoFillBackground(False)
        self.srchBtn.setStyleSheet("background:rgb(255,255,255)")
        self.srchBtn.setText("")
        self.srchBtn.clicked.connect(self.search)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/srch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.srchBtn.setIcon(icon)
        self.srchBtn.setIconSize(QtCore.QSize(40, 40))
        self.srchBtn.setFlat(True)
        self.srchBtn.setObjectName("srchBtn")
        self.srchBtn.setToolTip('Search Record')
        self.horizontalLayout_8.addWidget(self.srchBtn)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.verticalLayout_2.addWidget(self.srchFrame)
        #edit section
        self.editFrame = QtWidgets.QFrame(self.searchArea)
        self.editFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.editFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editFrame.setObjectName("editFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.editFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.editFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        #basic detail label
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgb(255, 170, 0);\n"
                                "border-top-right-radius:15px;\n"
                                "border-top-left-radius:15px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        #load animation
        self.loadFrame = QtWidgets.QFrame(self.frame)
        self.loadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadFrame.setObjectName("loadFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.loadFrame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        #load section
        self.load = QtWidgets.QLabel(self.loadFrame)
        self.load.setMaximumSize(QtCore.QSize(75, 75))
        self.load.setScaledContents(True)
        self.load.setObjectName("load")
        self.movie = QtGui.QMovie("icons/load.gif")
        self.load.setMovie(self.movie)
        self.load.hide()
        self.horizontalLayout_9.addWidget(self.load)
        self.horizontalLayout_2.addWidget(self.loadFrame)
        self.horizontalLayout.addWidget(self.frame)
        #button section
        self.btnFrame = QtWidgets.QFrame(self.editFrame)
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.btnFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #save button
        self.saveBtn = QtWidgets.QPushButton(self.btnFrame)
        self.saveBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.clicked.connect(self.save)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon1)
        self.saveBtn.setIconSize(QtCore.QSize(40, 40))
        self.saveBtn.setFlat(True)
        self.saveBtn.setObjectName("saveBtn")
        self.saveBtn.setToolTip('Save current Record')
        self.horizontalLayout_3.addWidget(self.saveBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        #edit button
        self.editBtn = QtWidgets.QPushButton(self.btnFrame)
        self.editBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.editBtn.setFont(font)
        self.editBtn.clicked.connect(self.edit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editBtn.setIcon(icon2)
        self.editBtn.setIconSize(QtCore.QSize(50, 50))
        self.editBtn.setFlat(True)
        self.editBtn.setObjectName("editBtn")
        self.editBtn.setToolTip('Edit current Record')
        self.horizontalLayout_3.addWidget(self.editBtn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        #add button
        self.addBtn = QtWidgets.QPushButton(self.btnFrame)
        self.addBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.clicked.connect(self.add)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon3)
        self.addBtn.setIconSize(QtCore.QSize(40, 40))
        self.addBtn.setFlat(True)
        self.addBtn.setObjectName("addBtn")
        self.addBtn.setToolTip('Add New Record')
        self.horizontalLayout_3.addWidget(self.addBtn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        #delete button
        self.deleteBtn = QtWidgets.QPushButton(self.btnFrame)
        self.deleteBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deleteBtn.setFont(font)
        self.deleteBtn.clicked.connect(self.delete)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBtn.setIcon(icon3)
        self.deleteBtn.setIconSize(QtCore.QSize(40, 40))
        self.deleteBtn.setFlat(True)
        self.deleteBtn.setObjectName("deleteBtn")
        self.deleteBtn.setToolTip('Delete current Record')
        self.horizontalLayout_3.addWidget(self.deleteBtn, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.btnFrame, 0, QtCore.Qt.AlignRight)

        self.verticalLayout_2.addWidget(self.editFrame)
        self.verticalLayout.addWidget(self.searchArea)
        #detail area
        self.detailArea = QtWidgets.QFrame(studFrame)
        self.detailArea.setMaximumSize(QtCore.QSize(16777215,16777215))
        self.detailArea.setStyleSheet("background:#ffffff")
        self.detailArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.detailArea.setObjectName("detailArea")
        self.gridLayout = QtWidgets.QGridLayout(self.detailArea)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        #attendence section
        self.attendence = QtWidgets.QFrame(self.detailArea)
        self.attendence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attendence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attendence.setObjectName("attendence")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.attendence)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.attendenceTxt = QtWidgets.QFrame(self.attendence)
        self.attendenceTxt.setMaximumSize(QtCore.QSize(500, 50))
        self.attendenceTxt.setStyleSheet("background:rgb(255, 170, 0);\n"
                                                "border-radius:15px;")
        self.attendenceTxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attendenceTxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attendenceTxt.setObjectName("attendenceTxt")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.attendenceTxt)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logo = QtWidgets.QLabel(self.attendenceTxt)
        self.logo.setMaximumSize(QtCore.QSize(40, 40))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("icons/7.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_4.addWidget(self.logo)
        self.txt = QtWidgets.QLabel(self.attendenceTxt)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt.setFont(font)
        self.txt.setObjectName("txt")
        self.horizontalLayout_4.addWidget(self.txt)
        self.verticalLayout_4.addWidget(self.attendenceTxt)
        #attendance frame
        self.attendanceFrame = QtWidgets.QFrame(self.attendence)
        self.attendanceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attendanceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attendanceFrame.setObjectName("attendanceFrame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.attendanceFrame)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.at1 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at1.setFont(font)
        self.at1.setStyleSheet("")
        self.at1.setAlignment(QtCore.Qt.AlignCenter)
        self.at1.setReadOnly(True)
        self.at1.setObjectName("at1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.at1)
        self.label_24 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.at2 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at2.setFont(font)
        self.at2.setStyleSheet("")
        self.at2.setAlignment(QtCore.Qt.AlignCenter)
        self.at2.setReadOnly(True)
        self.at2.setObjectName("at2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.at2)
        self.label_25 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.at3 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at3.setFont(font)
        self.at3.setAlignment(QtCore.Qt.AlignCenter)
        self.at3.setReadOnly(True)
        self.at3.setObjectName("at3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.at3)
        self.label_26 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.at4 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at4.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at4.setFont(font)
        self.at4.setAlignment(QtCore.Qt.AlignCenter)
        self.at4.setReadOnly(True)
        self.at4.setObjectName("at4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.at4)
        self.label_27 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.at5 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at5.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at5.setFont(font)
        self.at5.setAlignment(QtCore.Qt.AlignCenter)
        self.at5.setReadOnly(True)
        self.at5.setObjectName("at5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.at5)
        self.label_28 = QtWidgets.QLabel(self.attendanceFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.at6 = QtWidgets.QLineEdit(self.attendanceFrame)
        self.at6.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.at6.setFont(font)
        self.at6.setAlignment(QtCore.Qt.AlignCenter)
        self.at6.setReadOnly(True)
        self.at6.setObjectName("at6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.at6)
        self.verticalLayout_4.addWidget(self.attendanceFrame)
        self.gridLayout.addWidget(self.attendence, 1, 0, 1, 1)
        #student detail section
        self.stud = QtWidgets.QFrame(self.detailArea)
        self.stud.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stud.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stud.setObjectName("stud")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stud)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.studTxt = QtWidgets.QFrame(self.stud)
        self.studTxt.setMaximumSize(QtCore.QSize(500, 50))
        self.studTxt.setStyleSheet("background:rgb(255, 170, 0);\n"
                                        "border-radius:15px;")
        self.studTxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.studTxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.studTxt.setObjectName("studTxt")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.studTxt)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.logo_4 = QtWidgets.QLabel(self.studTxt)
        self.logo_4.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_4.setText("")
        self.logo_4.setPixmap(QtGui.QPixmap("icons/7.png"))
        self.logo_4.setScaledContents(True)
        self.logo_4.setObjectName("logo_4")
        self.horizontalLayout_7.addWidget(self.logo_4)
        self.txt_4 = QtWidgets.QLabel(self.studTxt)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_4.setFont(font)
        self.txt_4.setObjectName("txt_4")
        self.horizontalLayout_7.addWidget(self.txt_4)
        self.verticalLayout_7.addWidget(self.studTxt)
        self.studFrame_2 = QtWidgets.QFrame(self.stud)
        self.studFrame_2.setStyleSheet("")
        self.studFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.studFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.studFrame_2.setObjectName("studFrame_2")
        self.formLayout = QtWidgets.QFormLayout(self.studFrame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.regNo = QtWidgets.QLineEdit(self.studFrame_2)
        self.regNo.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.regNo.setFont(font)
        self.regNo.setStyleSheet("")
        self.regNo.setAlignment(QtCore.Qt.AlignCenter)
        self.regNo.setReadOnly(True)
        self.regNo.setObjectName("regNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.regNo)
        self.label_5 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.name = QtWidgets.QLineEdit(self.studFrame_2)
        self.name.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_6 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.roll = QtWidgets.QLineEdit(self.studFrame_2)
        self.roll.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.roll.setFont(font)
        self.roll.setAlignment(QtCore.Qt.AlignCenter)
        self.roll.setReadOnly(True)
        self.roll.setObjectName("roll")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roll)
        self.label_7 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.course = QtWidgets.QLineEdit(self.studFrame_2)
        self.course.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.course.setFont(font)
        self.course.setAlignment(QtCore.Qt.AlignCenter)
        self.course.setReadOnly(True)
        self.course.setObjectName("course")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.course)
        self.label_9 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.mob = QtWidgets.QLineEdit(self.studFrame_2)
        self.mob.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.mob.setFont(font)
        self.mob.setAlignment(QtCore.Qt.AlignCenter)
        self.mob.setReadOnly(True)
        self.mob.setObjectName("mob")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mob)
        self.label_10 = QtWidgets.QLabel(self.studFrame_2)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.address = QtWidgets.QLineEdit(self.studFrame_2)
        self.address.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.address.setFont(font)
        self.address.setAlignment(QtCore.Qt.AlignCenter)
        self.address.setReadOnly(True)
        self.address.setObjectName("address")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.address)
        self.verticalLayout_7.addWidget(self.studFrame_2)
        self.gridLayout.addWidget(self.stud, 0, 0, 1, 1)
        #fee section
        self.fee = QtWidgets.QFrame(self.detailArea)
        self.fee.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fee.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fee.setObjectName("fee")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fee)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.feeTxt = QtWidgets.QFrame(self.fee)
        self.feeTxt.setMaximumSize(QtCore.QSize(500, 50))
        self.feeTxt.setStyleSheet("background:rgb(255, 170, 0);\n"
                                        "border-radius:15px;")
        self.feeTxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.feeTxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feeTxt.setObjectName("feeTxt")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.feeTxt)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logo_2 = QtWidgets.QLabel(self.feeTxt)
        self.logo_2.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("icons/7.png"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setObjectName("logo_2")
        self.horizontalLayout_5.addWidget(self.logo_2)
        self.txt_2 = QtWidgets.QLabel(self.feeTxt)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_2.setFont(font)
        self.txt_2.setObjectName("txt_2")
        self.horizontalLayout_5.addWidget(self.txt_2)
        self.verticalLayout_5.addWidget(self.feeTxt)
        self.feeFrame = QtWidgets.QFrame(self.fee)
        self.feeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.feeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feeFrame.setObjectName("feeFrame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.feeFrame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.f1 = QtWidgets.QLineEdit(self.feeFrame)
        self.f1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f1.setFont(font)
        self.f1.setStyleSheet("")
        self.f1.setAlignment(QtCore.Qt.AlignCenter)
        self.f1.setReadOnly(True)
        self.f1.setObjectName("f1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.f1)
        self.label_18 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.f2 = QtWidgets.QLineEdit(self.feeFrame)
        self.f2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f2.setFont(font)
        self.f2.setStyleSheet("")
        self.f2.setAlignment(QtCore.Qt.AlignCenter)
        self.f2.setReadOnly(True)
        self.f2.setObjectName("f2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.f2)
        self.label_19 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.f3 = QtWidgets.QLineEdit(self.feeFrame)
        self.f3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f3.setFont(font)
        self.f3.setAlignment(QtCore.Qt.AlignCenter)
        self.f3.setReadOnly(True)
        self.f3.setObjectName("f3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.f3)
        self.label_20 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.f4 = QtWidgets.QLineEdit(self.feeFrame)
        self.f4.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f4.setFont(font)
        self.f4.setAlignment(QtCore.Qt.AlignCenter)
        self.f4.setReadOnly(True)
        self.f4.setObjectName("f4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.f4)
        self.label_21 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.f5 = QtWidgets.QLineEdit(self.feeFrame)
        self.f5.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f5.setFont(font)
        self.f5.setAlignment(QtCore.Qt.AlignCenter)
        self.f5.setReadOnly(True)
        self.f5.setObjectName("f5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.f5)
        self.label_22 = QtWidgets.QLabel(self.feeFrame)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.f6 = QtWidgets.QLineEdit(self.feeFrame)
        self.f6.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.f6.setFont(font)
        self.f6.setAlignment(QtCore.Qt.AlignCenter)
        self.f6.setReadOnly(True)
        self.f6.setObjectName("f6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.f6)
        self.verticalLayout_5.addWidget(self.feeFrame)
        self.gridLayout.addWidget(self.fee, 0, 2, 1, 1)
        #remark section
        self.remark = QtWidgets.QFrame(self.detailArea)
        self.remark.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remark.setFrameShadow(QtWidgets.QFrame.Raised)
        self.remark.setObjectName("remark")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.remark)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.remarkTxt = QtWidgets.QFrame(self.remark)
        self.remarkTxt.setMaximumSize(QtCore.QSize(500, 50))
        self.remarkTxt.setStyleSheet("background:rgb(255, 170, 0);\n"
                                        "border-radius:15px;")
        self.remarkTxt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remarkTxt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.remarkTxt.setObjectName("remarkTxt")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.remarkTxt)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logo_3 = QtWidgets.QLabel(self.remarkTxt)
        self.logo_3.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_3.setText("")
        self.logo_3.setPixmap(QtGui.QPixmap("icons/7.png"))
        self.logo_3.setScaledContents(True)
        self.logo_3.setObjectName("logo_3")
        self.horizontalLayout_6.addWidget(self.logo_3)
        self.txt_3 = QtWidgets.QLabel(self.remarkTxt)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_3.setFont(font)
        self.txt_3.setObjectName("txt_3")
        self.horizontalLayout_6.addWidget(self.txt_3)
        self.verticalLayout_6.addWidget(self.remarkTxt)
        self.remarkFrame = QtWidgets.QFrame(self.remark)
        self.remarkFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remarkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.remarkFrame.setObjectName("remarkFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.remarkFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.remarkPT = QtWidgets.QPlainTextEdit(self.remarkFrame)
        self.remarkPT.setMaximumSize(QtCore.QSize(500, 100))
        self.remarkPT.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.remarkPT.setFont(font)
        self.remarkPT.setObjectName("remarkPT")
        self.verticalLayout_3.addWidget(self.remarkPT, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.remarkFrame)
        self.gridLayout.addWidget(self.remark, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.detailArea)

        self.prsnlInps=[self.regNo,self.roll,self.name,self.course,self.mob,self.address]
        self.feeInps=[self.f1,self.f2,self.f3,self.f4,self.f5,self.f6]
        self.atndInps=[self.at1,self.at2,self.at3,self.at4,self.at5,self.at6]
        self.tables=['Student','Fees','Attendance','Remark']

        self.retranslateUi(studFrame)
        QtCore.QMetaObject.connectSlotsByName(studFrame)
    def search(self):
        self.load.show()
        self.movie.start()
        self.lineReadOnly(True)
        srchId = self.regNoInp.toPlainText()
        if not srchId == '' and srchId.isdigit():
            db = SMSDB()
            records=[]
            if db.stud_exist(srchId):
                for table in self.tables:records.append(db.fetchStud(table,srchId))
                for item,line in zip(records[0],self.prsnlInps):line.setText(item)
                rec=records[1]
                rec=rec[1:]
                for item,line in zip(rec,self.feeInps):line.setText(item)
                rec=records[2]
                rec=rec[1:]
                for item,line in zip(rec,self.atndInps):line.setText(item)
                self.remarkPT.setPlainText(records[3][1])
            else:show_msg('User not Found.')
            db.conn_close()
        else:show_msg('Enter valid input.')
        self.movie.stop()
        self.load.hide()
    def add(self):
        self.recClose()
        self.lineReadOnly(False)
        show_msg('Ready to add fields.')
    def save(self):
        if self.recOpen():
            if not self.regNo.isReadOnly():
                # fetching all data from form
                reg = self.regNo.text()
                nm = self.name.text()
                roll= self.roll.text()
                no = self.mob.text()
                sub=self.course.text()
                add=self.address.text()
                fee,atnd=[],[]
                for f in self.feeInps:fee.append(f.text())
                for a in self.atndInps:atnd.append(a.text())
                rmrk=self.remarkPT.toPlainText()
                # applying validations
                for name in nm.split():
                    if not name.isalpha():
                        show_msg('Enter valid name.')
                        break
                if not reg.isdigit():show_msg('Enter valid Registration No.')
                elif not roll.isdigit():show_msg('Enter valid Roll No.')
                elif not no.isdigit():show_msg('Enter valid Mobile No.')
                elif len(no) != 10:show_msg('Enter valid length Mobile No.')
                elif not sub.isalpha():show_msg('Enter valid Course.')
                elif not add.isalpha():show_msg('Enter valid Address.')
                elif not fee[0] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 1')
                elif not fee[1] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 2')
                elif not fee[2] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 3')
                elif not fee[3] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 4')
                elif not fee[4] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 5')
                elif not fee[5] in ('Paid','Unpaid'):show_msg('Enter valid Fee status for Sem 6')
                elif not atnd[0].isdigit():show_msg('Enter valid Attendance for Sem 1')
                elif not atnd[1].isdigit():show_msg('Enter valid Attendance for Sem 2')
                elif not atnd[2].isdigit():show_msg('Enter valid Attendance for Sem 3')
                elif not atnd[3].isdigit():show_msg('Enter valid Attendance for Sem 4')
                elif not atnd[4].isdigit():show_msg('Enter valid Attendance for Sem 5')
                elif not atnd[5].isdigit():show_msg('Enter valid Attendance for Sem 6')
                else:
                    db = SMSDB()  # connnecting DB
                    if db.insertStud(reg,nm,roll,no,sub,add,fee,atnd,rmrk):show_msg('Student Record created.')
                    else:
                        if confirm_msg('User already exist.\nWant to Update Record'):
                            db.updateStud(reg,nm,roll,no,sub,add,fee,atnd,rmrk)
                            show_msg('Record Updated.')
                    db.conn_close()  # disconnecting DB
                    self.recClose()
                    self.lineReadOnly(True)
            else:pass
        else:show_msg('No Record to Save.')
    def edit(self):
        if self.recOpen():
            self.lineReadOnly(False)
            show_msg('Ready to edit fields.')
        else:show_msg('No Record to Edit.')
    def delete(self):
        if self.recOpen():
            if confirm_msg('Confirm to Delete'):
                db=SMSDB()
                regNo=self.regNo.text()
                for table in self.tables:db.deleteStud(table,regNo)
                show_msg('Record Deleted')
                db.conn_close()
                self.recClose()
                self.lineReadOnly(True)
        else:show_msg('No Record to Delete.')
    def lineReadOnly(self,state):
        for lineEdit in (self.prsnlInps,self.feeInps,self.atndInps):
            for l in lineEdit:
                l.setReadOnly(state)
        self.remarkPT.setReadOnly(state)
    def recOpen(self):
        flag=False
        for lineEdit in (self.prsnlInps,self.feeInps,self.atndInps):
            for l in lineEdit:
                if not l.text()=='':
                    flag = True
                    break
        return flag
    def recClose(self):
        for lineEdit in (self.prsnlInps,self.feeInps,self.atndInps):
            for l in lineEdit:
                l.clear()
        self.regNoInp.clear()
        self.remarkPT.clear()
    def retranslateUi(self, studFrame):
        _translate = QtCore.QCoreApplication.translate
        studFrame.setWindowTitle(_translate("studFrame", "studFrame"))
        self.reg.setText(_translate("studFrame", "Registration No :  "))
        self.regNoInp.setPlaceholderText(_translate("studFrame", "Enter Registration Number"))
        self.label.setText(_translate("studFrame", "Basic Details"))
        self.txt.setText(_translate("studFrame", "Attendence"))
        self.label_23.setText(_translate("studFrame", "Semester 1"))
        self.at1.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_24.setText(_translate("studFrame", "Semester 2"))
        self.at2.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_25.setText(_translate("studFrame", "Semester 3"))
        self.at3.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_26.setText(_translate("studFrame", "Semester 4"))
        self.at4.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_27.setText(_translate("studFrame", "Semester 5"))
        self.at5.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_28.setText(_translate("studFrame", "Semester 6"))
        self.at6.setPlaceholderText(_translate("studFrame", "N/A"))
        self.txt_4.setText(_translate("studFrame", "Personal Details"))
        self.label_8.setText(_translate("studFrame", "Reg No"))
        self.regNo.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_5.setText(_translate("studFrame", "Name"))
        self.name.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_6.setText(_translate("studFrame", "Roll"))
        self.roll.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_7.setText(_translate("studFrame", "Course"))
        self.course.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_9.setText(_translate("studFrame", "Contact"))
        self.mob.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_10.setText(_translate("studFrame", "Address"))
        self.address.setPlaceholderText(_translate("studFrame", "N/A"))
        self.txt_2.setText(_translate("studFrame", "Fee Details"))
        self.label_17.setText(_translate("studFrame", "Semester 1"))
        self.f1.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_18.setText(_translate("studFrame", "Semester 2"))
        self.f2.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_19.setText(_translate("studFrame", "Semester 3"))
        self.f3.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_20.setText(_translate("studFrame", "Semester 4"))
        self.f4.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_21.setText(_translate("studFrame", "Semester 5"))
        self.f5.setPlaceholderText(_translate("studFrame", "N/A"))
        self.label_22.setText(_translate("studFrame", "Semester 6"))
        self.f6.setPlaceholderText(_translate("studFrame", "N/A"))
        self.txt_3.setText(_translate("studFrame", "Remark"))
        self.remarkPT.setPlaceholderText(_translate("studFrame", "your remark"))
"""This is for trial run""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studFrame = QtWidgets.QFrame()
    ui = Ui_studFrame()
    ui.setupUi(studFrame)
    studFrame.show()
    sys.exit(app.exec_())
"""